import { streamSummary } from '../api'
import { useLlmStream } from '../useLlmStream'
import type { AppConfig, PaperDetail, SummaryFields } from '../types'
import LlmNotice from './LlmNotice'
import Markdown from './Markdown'
import RichText from './RichText'

interface Props {
  paper: PaperDetail
  llm: AppConfig | null
  onSummary: (fields: SummaryFields) => void
}

export default function SummaryPanel({ paper, llm, onSummary }: Props) {
  const stream = useLlmStream()

  function generate() {
    stream.start(
      (onEvent, signal) => streamSummary(paper.id, onEvent, signal),
      (e) => {
        if (!e.paper) return
        const { summary, summary_model, summary_context, summary_created_at } = e.paper
        onSummary({ summary, summary_model, summary_context, summary_created_at })
      },
    )
  }

  // A failed regeneration discards its partial text and shows the saved summary again.
  const live = stream.running
  return (
    <section className="card panel">
      <div className="panel-head">
        <h2>Summary</h2>
        <button
          className={paper.summary ? 'btn small' : 'btn small primary'}
          onClick={generate}
          disabled={stream.running || llm?.llm_ready === false}
        >
          {stream.running ? 'Generating…' : paper.summary ? 'Regenerate' : 'Generate summary'}
        </button>
      </div>

      {llm?.llm_ready === false && <LlmNotice llm={llm} />}
      {stream.context?.truncated && (
        <p className="note">The paper is very long, so only its first part was sent to the model.</p>
      )}
      {stream.error && (
        <div className="alert error">
          <RichText text={stream.error} />
        </div>
      )}

      {live ? (
        stream.text ? (
          <Markdown>{stream.text}</Markdown>
        ) : (
          <p className="muted thinking">Reading the paper and writing a summary. This can take up to a minute…</p>
        )
      ) : paper.summary ? (
        <>
          <Markdown>{paper.summary}</Markdown>
          <p className="muted provenance">
            Generated by {paper.summary_model} from the{' '}
            {paper.summary_context === 'full_text' ? 'full text' : 'abstract only'}
            {paper.summary_created_at && ` · ${new Date(paper.summary_created_at).toLocaleString()}`}
          </p>
        </>
      ) : (
        !stream.error && (
          <p className="muted">
            No summary yet. The assistant reads the paper itself, not just its title and abstract.
          </p>
        )
      )}
    </section>
  )
}
